#ifndef HM_COMMAND_H
#define HM_COMMAND_H

#include "core/core.h"

typedef enum CommandType
{
	HM_COMMAND_TYPE_NONE = 0,
	HM_COMMAND_TYPE_QUIT_BIT = BIT(0),
	HM_COMMAND_TYPE_PUSH_GAMESTATE_PLAY_BIT = BIT(1),
	HM_COMMAND_TYPE_PUSH_GAMESTATE_LOCATION_BIT = BIT(2),
	HM_COMMAND_TYPE_PUSH_GAMESTATE_TRAVEL_BIT = BIT(3),
	HM_COMMAND_TYPE_TRAVEL_BIT = BIT(4),
	HM_COMMAND_TYPE_CREATE_NEW_GAME_BIT = BIT(5),
	HM_COMMAND_TYPE_LOAD_GAME_BIT = BIT(6),
	HM_COMMAND_TYPE_PUSH_GAMESTATE_OPTIONS_BIT = BIT(7),
	HM_COMMAND_TYPE_PUSH_GAMESTATE_LANGUAGE_BIT = BIT(8),
	HM_COMMAND_TYPE_CHANGE_LANGUAGE_BIT = BIT(9),
	HM_COMMAND_TYPE_PUSH_GAMESTATE_CONTROLS_BIT = BIT(10),
	HM_COMMAND_TYPE_SET_KEYBIND_BIT = BIT(11),
	HM_COMMAND_TYPE_PUSH_GAMESTATE_YES_NO_POPUP_BIT = BIT(12),
	HM_COMMAND_TYPE_POP_GAMESTATE_BIT = BIT(13)
} CommandType;

typedef struct Command
{
	const char* name_id;
	CommandType type;
} Command;

#endif